import type { Metadata } from "next";
import "./globals.css";
import RecoilRootComponent from "@/components/context/recoilroot";
import { Toaster } from "sonner";
import { QueryClientProviderComponent } from "@/components/context/queryClientComponent";
import { BackgroundMusic } from "@/components/shared/BackgroundMusic";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Quicksand } from "next/font/google";
import { cn } from "@/lib/utils";
import { LanguageSelector } from "@/components/game/shared/languageSelector";

const quicksand = Quicksand({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(quicksand.className, "bg-purple-light")}>
        <Toaster position="top-center" richColors />
        <QueryClientProviderComponent>
          <RecoilRootComponent>
            <div className="flex w-full relative">
              <div className="absolute right-4 top-4 z-10">
                <LanguageSelector />
              </div>
              {children}
            </div>
            <BackgroundMusic />
          </RecoilRootComponent>
        </QueryClientProviderComponent>
      </body>
    </html>
  );
}
